### ISSUE TITLE
💥 [DevOps] In Travis And GitHub CI Move Linting In Front Of Testing

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#4028]
## :fire: DevOps ticket

In Travis and GitHub CI move linting in front of testing.

*Is this possible or do we need the docker containers first build?*
If it seems not possible. Why we can do it with the locales check?

### Motive

Very often the linting check fails. Therefore it would be cool to have the linting at the beginning of the build aside the locales check so we can see problems quick, stop the build, and fix the linting.
That saves us Travis credits and accelerates the development process.

### Related issues

None

### Implementation

Change file `.github/workflows/ci.yml`.

### Validation

Check the build process.

### Additional context

None

**Comment by Mogge** [comment]
Good idea! I hope it works

**Comment by ulfgebhardt** [comment]
I am against this change. Even tho the suggested change makes sense to speed up things, the current approach is uniform for everything: run on docker. Everything is tested within docker. This will allow easy port to any build environment. Since we can parallelize most of the processes and the whole test build takes 12min, I believe this is acceptable.
Discuss!
