### ISSUE TITLE
🚀 [Feature] Send An E-Mail If User Gets A Notification

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#4326]
## :rocket: Feature

Have the possibility to send an e-mail to the user if they get a notification.

### User Problem

```gherkin
Feature: Send a notification e-mail to a user
  As a user
  I like to get an e-mail send if I get a notification.
  In order that I get notified even if I'm not logged in.
```

### Implementation

Have a setting, where a user can set if they like to get an e-mail send if they get a notification.

### Design & Layout

None

### Validation

None

### Additional Informations

related #4235 
see #4675

**Comment by ulfgebhardt** [comment]
Also consider Push notifications for the Progressive Web App

**Comment by hermann-san** [comment]
A few thoughts about E-mail notifications

- One problem with e-mail notifications is that people may get overwhelmed with e-mails, in the case they receive multiple notifications in a day. This may provoke that inexperienced people unsubscribe from E-mail notifications altogether instead of changing the notification options.  Hence I would find it useful to limit the number notifications from the beginning to 2 E-mails per week or one E-mail per day. 

- It would be good to be able to configure E-mail notifications options and mention it in the e-mail. E.g. immediate notification, once a day, twice a week, once a week, once a month.

- Users who don't get notifications frequently may receive a bi-weekly or monthly digest e-mail of a few, new selected, popular articles from  the network.

**Comment by sushidave** [comment]
Change request:

1) Default for the checkbox in the user account settings: selected

2) Show the this text at the bottom of the email message. The text in square brackets links to the account settings page:

en: 
_No longer want to receive e-mails for new notifications? Turn them off in your [account settings]._

de:
_Möchtest Du bei neuen Benachrichtigungen keine E-Mails mehr erhalten, dann schalte sie in den [Kontoeinstellungen] aus._

3) Provide a link to the account settings page on top of the notifications page. For this purpose, shall we use the gear weels icon of the user menu?
