### ISSUE TITLE
💥 [DevOps] Remove Cucumber tests

### ISSUE THREAD

**Issue by ulfgebhardt** [Ocelot-Social-Community/Ocelot-Social#4384]
## 💥 DevOps ticket

Remove Cucumber tests

The cucumber tests do end to end tests for the GraphQL API, this should be covered by the backend unit tests and the cypress end to end tests.

Can you give me feedback on that @roschaefer ?

**Comment by roschaefer** [comment]
Cucumber tests are human-readable. So, you can test your API with cucumber in order to create *executable documentation*. We used cucumber tests to describe the API for ActivityPub, ie. other developers can see what they have to send from their endpoints without looking into the code.

Ping @mastercuber

**Comment by ulfgebhardt** [comment]
I ask because it seem incomplete and infunctional. Cypress is running again <3

**Comment by roschaefer** [comment]
I haven't checked in for a while. But obviously the tests were not implemented yet, because the implementation was missing. E.g. I sketched the cucumber tests after reading the activity-pub spec https://www.w3.org/TR/activitypub/ and the development team would have to implement it. E.g. the cucumber tests were the interface with @mastercuber and his master thesis.

**Comment by ulfgebhardt** [comment]
So would you consider them useful and is that usefulness limited to activity pub or do we need them for other things? @roschaefer

**Comment by roschaefer** [comment]
It's useful if you want to document your ActivityPub API for external developers. If you want to document other software tests in a human-friendly way, you can use it for them, too. See: https://cucumber.io/docs/bdd/

**Comment by Mastercuber** [comment]
The Activity Component still needs further development. Eg. The HTTP Signature needs to include a mandatory digest header to be able to communicate with mastodon at all (see [here](https://github.com/dariusk/express-activitypub/issues/12). Also a PR is referenced)

The Test, if they are working, I would consider useful, especially, like mentioned from @roschaefer, for other developers who want to exchange information from their projects to OS or vice versa. I would consider it useful in such cases to look at the tests to get a grasp of what they need to successfully communicate with OS. 
But not only for developers of other projects, but also for OS developers and non developers it is useful for the understanding of the functionality the ActivityPub component is capable of. 

One improvement could be to change "I expect the status code to be 200" to "I expect the request to be successful", because the Cucumber Features are also intended for other project members than developers. The latter sentence is less technical and more understandable.

Another improvement should be to rewrite the description of the features to clearly point out what this test is for and what scenarios are covered by the test.

And yeah, they are incomplete and infunctional.

**Comment by ulfgebhardt** [comment]
I thank you for your insights @roschaefer & @Mastercuber - I will keep the cucumber and have it implemented for activity pub <3
