### ISSUE TITLE
🔧 [Refactor] Long Words Wrapped

### ISSUE THREAD

**Issue by ogerly** [Ocelot-Social-Community/Ocelot-Social#5427]
## 🔧 Refactor
Long words should be wrapped. 
Please check the GroupProfile and UserProfile. 

![Bildschirmfoto vom 2022-09-29 14-49-39](https://user-images.githubusercontent.com/1324583/193036880-1f357c7a-8feb-44f4-add1-3bc629787edd.png)

see: https://discord.com/channels/@me/572406810468941836/1025027302494568448

**Comment by Snow-Bull** [comment]
Hey, Can I work on this issue?

**Comment by Tirokk** [comment]
Hey @Snow-Bull ,

sorry that I have overseen your question !!! 🙏🏼

Yes for sure you can take over. That’s great! 🤗
I assigned you to this issue.

I cared for your invitation to our community as volunteer via an e-mail invitation you can accept.

Our conversation runs over our discord server:
https://discord.gg/AJSX9DCSUA
There we have usually from Monday to Thursday a Daily Standup at UTC 09:30 am (CEST 11:30 am) in the Office Cube.

Please don’t compare from your fork to this repository, in case, because the publish action will fail, because of permission problems with the credentials.
Just push your branch directly to our repo and compare to the master.
If you accept the invitation then you’ll have the right todo so. 😉
