### ISSUE TITLE
💬 [Question] Webapp – Event, Datetime – Leave the Time Away if there is no Time?

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#6463]
## 💬 Question

Webapp – Event, Datetime – Leave the Time Away if there is no Time?

Because it looks odd if we have `0:00h–0:00h` or `19.06. 0:00h – 25.06.2023 0:00h`.

- what means that there is no time?
- should we have a checkbox?

I guess we cannot just say that there is no time if it's 0:00h.

<img width="375" alt="Bildschirmfoto 2023-06-16 um 22 00 02" src="https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/25344101/7a8c850f-2fa1-4bfc-8ac0-21ac90e06f7e">

**Comment by Elweyn** [comment]
- [ ] 🚀 [Feature][Backend] Test mutation create and update Post with a Date instead of DateTime
- [ ] 🚀 [Feature][Backend] Refactor mutation logic of create and update Post for the current date
- [ ] 🚀 [Feature][Webapp] Create and Edit Event Page input DateTime split into two inputs
- [ ] 🚀 [Feature][Webapp] Overview and Teaser of events doesn't show time if time is empty
