### ISSUE TITLE
🐛 [Bug] Empty space after filename

### ISSUE THREAD

**Issue by Gauravtripathii** [Ocelot-Social-Community/Ocelot-Social#6765]
## 🐛 Bugreport
There is an empty space at 'deployment/src/old/volumes/volume-snapshots/neo4j-data-snapshot.yaml ', making it impossible to clone this repository. Just remove the space after 'yml'

**Comment by Tirokk** [comment]
Hey @Gauravtripathii ,

thanks for your pull request. That’s great! 🤗
I assigned you to this issue.

I cared for your invitation to our community as volunteer via an e-mail invitation you can accept.

Our conversation runs over our discord server:
https://discord.gg/AJSX9DCSUA
Please use our chat channel to ping me ( @wolle (Hamburg)#8013 ).

**!!!**
Please don’t compare from your fork to this repository, because the publish action will fail, because of permission problems with the credentials.
Just push your branch directly to our repo and compare to the master.
If you accept the invitation then you’ll have the right todo so. 😉
