### ISSUE TITLE
🐛 [Bug] The picture is updated when the post page is updated

### ISSUE THREAD

**Issue by Butonix** [Ocelot-Social-Community/Ocelot-Social#6823]
https://stage.ocelot.social/post/2992d9b1-715c-42db-8d22-bd2d2873f8c5/esse-similique-sequi-quod-consectetur-maxime-quia-cum-veritatis-voluptates

We update the page and the picture will change forever

**Comment by ulfgebhardt** [comment]
This is because seed data is used. The used url is actuall unstable since it uses [faker images](https://fakerjs.dev/api/image.html)

You can test this by opening one of the images url several times. This will result in different images every time:
https://source.unsplash.com/category/nature/640x480?random=eaa26ecf-fdcb-481c-9dda-c36bd6c47dfd

If you want to contribute you can adjust the seed mechanism to save the resulting stable url instead of the the unstable url in order to have a stable set after seed.
